name: Developer Testing

on:
  pull_request:
    branches: ['develop']

defaults:
  run:
    shell: bash

jobs:
  build_and_test:
    name: Test
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        java: [17]
    runs-on: ${{matrix.os}}
    steps:
      - run: git config --global core.autocrlf false
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: ${{matrix.java}}

      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.sbt
            ~/.ivy2/cache
            ~/.cache/coursier
          key: ${{ runner.os }}-sbt-cache-v2-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/build.properties') }}

      - name: Build
        run: |
          sbt setupPublishCore generateBuildCharacterPropertiesFile headerCheck publishLocal

      - name: Test
        run: |
          STARR=`cat buildcharacter.properties | grep ^maven.version.number | cut -d= -f2` && echo $STARR
          sbt -Dstarr.version=$STARR setupValidateTest test:compile info testAll
